version: "3"
services: 
  server:
      container_name: web-app-locations-front
      build: ./
      volumes:
        - ./:/usr/web-app-locations
        - /usr/web-app-locations/node_modules
      ports:
        - "5173:5173"